import { addDaysISO, todayISO } from "./format";
import type {
  Appointment,
  Conversation,
  Customer,
  CustomerRequest,
  Invoice,
  Job,
  Notification,
  Quote,
  ServiceCategory,
} from "./types";

export const BUSINESS = {
  name: "FixMate Plumbing & Repairs",
  owner: "Nompumelelo",
  city: "Port Elizabeth",
  phone: "041 555 0142",
  email: "hello@fixmate.co.za",
};

export const TECHNICIANS = ["Sipho Mabaso", "Mike Daniels", "Thandi Williams", "James Brown"];

export const SERVICES: ServiceCategory[] = [
  "Plumbing",
  "Electrical",
  "Painting",
  "Handyman",
  "General Repairs",
];

export const customers: Customer[] = [
  {
    id: "c1",
    name: "Sarah Johnson",
    phone: "082 445 1120",
    email: "sarah.johnson@gmail.com",
    address: "14 Marine Drive",
    suburb: "Humewood",
    notes: "Prefers WhatsApp. Has two dogs — call before arriving.",
    createdAt: addDaysISO(-210),
  },
  {
    id: "c2",
    name: "Mike Daniels",
    phone: "073 908 6641",
    email: "mdaniels@outlook.com",
    address: "8 Heugh Road",
    suburb: "Walmer",
    notes: "Landlord, manages 3 rental units.",
    createdAt: addDaysISO(-160),
  },
  {
    id: "c3",
    name: "Thandi Williams",
    phone: "060 221 7788",
    email: "thandi.w@yahoo.com",
    address: "22 Beach Road",
    suburb: "Summerstrand",
    notes: "Invoices must be emailed for body-corporate approval.",
    createdAt: addDaysISO(-120),
  },
  {
    id: "c4",
    name: "James Brown",
    phone: "084 310 5502",
    email: "jbrown@fastmail.com",
    address: "5 Cape Road",
    suburb: "Newton Park",
    notes: "Often needs after-hours appointments.",
    createdAt: addDaysISO(-75),
  },
  {
    id: "c5",
    name: "Lerato Mokoena",
    phone: "071 664 2287",
    email: "lerato.m@gmail.com",
    address: "31 Villiers Road",
    suburb: "Walmer",
    notes: "New customer from Facebook referral.",
    createdAt: addDaysISO(-18),
  },
];

export const jobs: Job[] = [
  {
    id: "j1",
    reference: "FM-JOB-1041",
    customerId: "c1",
    service: "Plumbing",
    title: "Fix leaking kitchen tap",
    description: "Kitchen mixer tap dripping, cupboard underneath getting wet.",
    status: "In Progress",
    priority: "High",
    appointmentDate: todayISO(),
    time: "09:00",
    durationMins: 60,
    technician: "Sipho Mabaso",
    amount: 620,
    location: "14 Marine Drive, Humewood",
    equipment: ["Plumbing tool kit", "Replacement washer", "Replacement mixer tap"],
    notes: "Customer sent a photo of water damage under the sink.",
  },
  {
    id: "j2",
    reference: "FM-JOB-1042",
    customerId: "c2",
    service: "Electrical",
    title: "Install ceiling light fixture",
    description: "New pendant light in dining room of rental unit 2.",
    status: "Scheduled",
    priority: "Medium",
    appointmentDate: todayISO(),
    time: "11:30",
    durationMins: 90,
    technician: "Mike Daniels",
    amount: 890,
    location: "8 Heugh Road, Walmer",
    equipment: ["Ladder", "Insulated screwdrivers", "Cable clips"],
    notes: "Certificate of compliance not included — qualified electrician to confirm on site.",
  },
  {
    id: "j3",
    reference: "FM-JOB-1043",
    customerId: "c3",
    service: "Painting",
    title: "Paint main bedroom",
    description: "Two coats, off-white, includes minor crack filling.",
    status: "Scheduled",
    priority: "Low",
    appointmentDate: todayISO(),
    time: "14:00",
    durationMins: 180,
    technician: "Thandi Williams",
    amount: 2450,
    location: "22 Beach Road, Summerstrand",
    equipment: ["Rollers & trays", "Drop sheets", "Crack filler"],
    notes: "Furniture to be moved by customer before arrival.",
  },
  {
    id: "j4",
    reference: "FM-JOB-1044",
    customerId: "c4",
    service: "Handyman",
    title: "Repair front door handle",
    description: "Handle loose, latch not catching properly.",
    status: "Scheduled",
    priority: "Medium",
    appointmentDate: todayISO(),
    time: "16:00",
    durationMins: 45,
    technician: "James Brown",
    amount: 380,
    location: "5 Cape Road, Newton Park",
    equipment: ["Hand tool kit", "Replacement latch"],
    notes: "",
  },
  {
    id: "j5",
    reference: "FM-JOB-1045",
    customerId: "c5",
    service: "Plumbing",
    title: "Burst geyser pipe",
    description: "Water leaking through ceiling from geyser overflow.",
    status: "New",
    priority: "Urgent",
    appointmentDate: addDaysISO(1),
    time: "08:00",
    durationMins: 120,
    technician: "Sipho Mabaso",
    amount: 0,
    location: "31 Villiers Road, Walmer",
    equipment: ["Pipe cutter", "Compression fittings", "Bucket & towels"],
    notes: "Customer advised to close the main water valve immediately.",
  },
  {
    id: "j6",
    reference: "FM-JOB-1046",
    customerId: "c2",
    service: "General Repairs",
    title: "Replace broken roof tiles",
    description: "Four cracked tiles above the garage.",
    status: "Quoted",
    priority: "Medium",
    appointmentDate: addDaysISO(2),
    time: "10:00",
    durationMins: 120,
    technician: "James Brown",
    amount: 1150,
    location: "8 Heugh Road, Walmer",
    equipment: ["Ladder", "Roof tiles", "Sealant"],
    notes: "",
  },
  {
    id: "j7",
    reference: "FM-JOB-1038",
    customerId: "c1",
    service: "Plumbing",
    title: "Unblock bathroom drain",
    description: "Slow draining shower.",
    status: "Completed",
    priority: "Medium",
    appointmentDate: addDaysISO(-6),
    time: "09:30",
    durationMins: 60,
    technician: "Sipho Mabaso",
    amount: 540,
    location: "14 Marine Drive, Humewood",
    equipment: ["Drain snake"],
    notes: "Recommend annual drain maintenance.",
  },
  {
    id: "j8",
    reference: "FM-JOB-1039",
    customerId: "c3",
    service: "Electrical",
    title: "Replace distribution board breaker",
    description: "Tripping breaker replaced.",
    status: "Completed",
    priority: "High",
    appointmentDate: addDaysISO(-9),
    time: "13:00",
    durationMins: 90,
    technician: "Mike Daniels",
    amount: 1280,
    location: "22 Beach Road, Summerstrand",
    equipment: ["Breaker", "Multimeter"],
    notes: "",
  },
  {
    id: "j9",
    reference: "FM-JOB-1040",
    customerId: "c4",
    service: "Painting",
    title: "Repaint garage door",
    description: "Sand, prime and two coats enamel.",
    status: "Completed",
    priority: "Low",
    appointmentDate: addDaysISO(-14),
    time: "08:30",
    durationMins: 240,
    technician: "Thandi Williams",
    amount: 1890,
    location: "5 Cape Road, Newton Park",
    equipment: ["Sander", "Enamel paint"],
    notes: "",
  },
  {
    id: "j10",
    reference: "FM-JOB-1037",
    customerId: "c5",
    service: "Handyman",
    title: "Mount TV bracket",
    description: "Wall-mounted 55 inch TV in lounge.",
    status: "Cancelled",
    priority: "Low",
    appointmentDate: addDaysISO(-3),
    time: "15:00",
    durationMins: 60,
    technician: "James Brown",
    amount: 450,
    location: "31 Villiers Road, Walmer",
    equipment: [],
    notes: "Customer postponed indefinitely.",
  },
];

export const quotes: Quote[] = [
  {
    id: "q1",
    number: "FM-001",
    customerId: "c1",
    jobId: "j1",
    service: "Plumbing",
    labour: 350,
    materials: 220,
    travel: 50,
    additional: 0,
    notes: "Includes replacement of mixer tap washer set.",
    status: "Accepted",
    createdAt: addDaysISO(-2),
  },
  {
    id: "q2",
    number: "FM-002",
    customerId: "c2",
    jobId: "j6",
    service: "General Repairs",
    labour: 700,
    materials: 400,
    travel: 50,
    additional: 0,
    notes: "Roof tile replacement above garage.",
    status: "Sent",
    createdAt: addDaysISO(-1),
  },
  {
    id: "q3",
    number: "FM-003",
    customerId: "c3",
    jobId: "j3",
    service: "Painting",
    labour: 1600,
    materials: 800,
    travel: 50,
    additional: 0,
    notes: "Main bedroom, two coats.",
    status: "Sent",
    createdAt: addDaysISO(-4),
  },
  {
    id: "q4",
    number: "FM-004",
    customerId: "c5",
    service: "Plumbing",
    labour: 900,
    materials: 620,
    travel: 80,
    additional: 150,
    notes: "Geyser overflow pipe replacement — after-hours callout.",
    status: "Draft",
    createdAt: todayISO(),
  },
];

export const invoices: Invoice[] = [
  {
    id: "i1",
    number: "INV-2041",
    customerId: "c1",
    jobId: "j7",
    jobTitle: "Unblock bathroom drain",
    amount: 540,
    status: "Paid",
    date: addDaysISO(-6),
  },
  {
    id: "i2",
    number: "INV-2042",
    customerId: "c3",
    jobId: "j8",
    jobTitle: "Replace distribution board breaker",
    amount: 1280,
    status: "Paid",
    date: addDaysISO(-9),
  },
  {
    id: "i3",
    number: "INV-2043",
    customerId: "c4",
    jobId: "j9",
    jobTitle: "Repaint garage door",
    amount: 1890,
    status: "Pending",
    date: addDaysISO(-4),
  },
  {
    id: "i4",
    number: "INV-2044",
    customerId: "c2",
    jobId: "j2",
    jobTitle: "Install ceiling light fixture",
    amount: 890,
    status: "Overdue",
    date: addDaysISO(-32),
  },
  {
    id: "i5",
    number: "INV-2045",
    customerId: "c1",
    jobId: "j1",
    jobTitle: "Fix leaking kitchen tap",
    amount: 620,
    status: "Pending",
    date: todayISO(),
  },
];

export const conversations: Conversation[] = [
  {
    id: "cv1",
    customerId: "c1",
    subject: "Leaking kitchen tap",
    unread: true,
    archived: false,
    messages: [
      {
        id: "m1",
        from: "customer",
        body: "Hi, my kitchen tap is leaking and the cupboard underneath is getting wet. Can someone come look today?",
        at: "07:42",
      },
      {
        id: "m2",
        from: "business",
        body: "Good morning Sarah, thanks for reaching out. We can be there at 09:00 this morning.",
        at: "07:55",
      },
      { id: "m3", from: "customer", body: "Perfect, thank you! I'll be home.", at: "08:01" },
    ],
  },
  {
    id: "cv2",
    customerId: "c5",
    subject: "Water coming through the ceiling",
    unread: true,
    archived: false,
    messages: [
      {
        id: "m4",
        from: "customer",
        body: "There is water dripping from the ceiling near the geyser, it started this morning and it's getting worse.",
        at: "06:20",
      },
    ],
  },
  {
    id: "cv3",
    customerId: "c2",
    subject: "Roof tile quote",
    unread: false,
    archived: false,
    messages: [
      {
        id: "m5",
        from: "customer",
        body: "Did you get a chance to price the roof tiles above the garage?",
        at: "Yesterday 16:10",
      },
      {
        id: "m6",
        from: "business",
        body: "Quote FM-002 has been sent through — R1,150 including travel.",
        at: "Yesterday 16:35",
      },
    ],
  },
  {
    id: "cv4",
    customerId: "c3",
    subject: "Bedroom painting date",
    unread: false,
    archived: false,
    messages: [
      {
        id: "m7",
        from: "customer",
        body: "Please confirm the painting is still happening at 14:00 today.",
        at: "08:15",
      },
    ],
  },
];

export const appointments: Appointment[] = [
  {
    id: "a1",
    jobId: "j1",
    customerId: "c1",
    title: "Fix leaking kitchen tap",
    service: "Plumbing",
    date: todayISO(),
    time: "09:00",
    durationMins: 60,
    priority: "High",
    location: "Humewood",
    notes: "",
  },
  {
    id: "a2",
    jobId: "j2",
    customerId: "c2",
    title: "Install light fixture",
    service: "Electrical",
    date: todayISO(),
    time: "11:30",
    durationMins: 90,
    priority: "Medium",
    location: "Walmer",
    notes: "",
  },
  {
    id: "a3",
    jobId: "j3",
    customerId: "c3",
    title: "Paint bedroom",
    service: "Painting",
    date: todayISO(),
    time: "14:00",
    durationMins: 180,
    priority: "Low",
    location: "Summerstrand",
    notes: "",
  },
  {
    id: "a4",
    jobId: "j4",
    customerId: "c4",
    title: "Repair door handle",
    service: "Handyman",
    date: todayISO(),
    time: "16:00",
    durationMins: 45,
    priority: "Medium",
    location: "Newton Park",
    notes: "",
  },
  {
    id: "a5",
    jobId: "j5",
    customerId: "c5",
    title: "Burst geyser pipe",
    service: "Plumbing",
    date: addDaysISO(1),
    time: "08:00",
    durationMins: 120,
    priority: "Urgent",
    location: "Walmer",
    notes: "Emergency callout",
  },
  {
    id: "a6",
    jobId: "j6",
    customerId: "c2",
    title: "Replace roof tiles",
    service: "General Repairs",
    date: addDaysISO(2),
    time: "10:00",
    durationMins: 120,
    priority: "Medium",
    location: "Walmer",
    notes: "",
  },
];

export const notifications: Notification[] = [
  {
    id: "n1",
    kind: "urgent",
    title: "Urgent job waiting",
    detail: "Burst geyser pipe at Lerato Mokoena (Walmer) needs a quote and confirmation.",
    at: "12 min ago",
    read: false,
  },
  {
    id: "n2",
    kind: "appointment",
    title: "Next appointment in 45 minutes",
    detail: "Install light fixture — Mike Daniels, Walmer at 11:30.",
    at: "20 min ago",
    read: false,
  },
  {
    id: "n3",
    kind: "quote",
    title: "3 quotes pending response",
    detail: "FM-002, FM-003 and FM-004 have not been accepted yet.",
    at: "1 hr ago",
    read: false,
  },
  {
    id: "n4",
    kind: "payment",
    title: "Payment received",
    detail: "INV-2042 — R1,280 from Thandi Williams.",
    at: "Yesterday",
    read: true,
  },
  {
    id: "n5",
    kind: "followup",
    title: "Follow-up overdue",
    detail: "Repaint garage door for James Brown was completed 14 days ago.",
    at: "Yesterday",
    read: true,
  },
  {
    id: "n6",
    kind: "waiting",
    title: "Request waiting too long",
    detail: "Website enquiry from Lerato Mokoena unanswered for 6 hours.",
    at: "2 days ago",
    read: true,
  },
];

export const requests: CustomerRequest[] = [
  {
    id: "r1",
    customerId: "c1",
    customerName: "Sarah Johnson",
    channel: "WhatsApp",
    body: "Hi, my kitchen tap is leaking and the cupboard underneath is getting wet.",
    receivedAt: "Today 07:42",
    handled: true,
  },
  {
    id: "r2",
    customerId: "c5",
    customerName: "Lerato Mokoena",
    channel: "Website",
    body: "There is water dripping from the ceiling near the geyser, it started this morning and it's getting worse. Please help urgently.",
    receivedAt: "Today 06:20",
    handled: false,
  },
  {
    id: "r3",
    customerId: "c4",
    customerName: "James Brown",
    channel: "Email",
    body: "Good day, the plug point in my garage stopped working and there is a burning smell. Also the front door handle is loose.",
    receivedAt: "Yesterday 18:05",
    handled: false,
  },
  {
    id: "r4",
    customerName: "Nosipho Dlamini",
    channel: "Phone",
    body: "Wants a price to paint a 3 bedroom house inside, moving in next month, not sure of colours yet.",
    receivedAt: "Yesterday 14:30",
    handled: false,
  },
];

export const revenueByMonth = [
  { month: "Mar", revenue: 12400 },
  { month: "Apr", revenue: 15200 },
  { month: "May", revenue: 13900 },
  { month: "Jun", revenue: 17600 },
  { month: "Jul", revenue: 16250 },
  { month: "Aug", revenue: 18450 },
];
